"""Export MLP weights as Rust const arrays (Section 7.2).

Converts the trained PyTorch MLP to flat int8-quantized weight arrays
that can be compiled directly into the SLM-OS binary. The generated
Rust code implements inference as 3 matrix multiplies + ReLU with
fixed-point arithmetic (no floating point in the hot path).

Target: ~4KB model size with int8 quantization.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import torch

from src.training.train_mlp import PageReplacementMLP


def export_mlp_to_rust(
    model: PageReplacementMLP,
    output_path: str | Path,
    quantize: bool = True,
) -> str:
    """Export MLP weights as Rust const arrays.

    Args:
        model: Trained PageReplacementMLP.
        output_path: Path to write the generated Rust file.
        quantize: If True, apply int8 quantization.

    Returns:
        The generated Rust source code as a string.
    """
    model.eval()
    state = model.state_dict()

    # Extract weight matrices and biases from the shared layers + classify head
    layers = _extract_layers(state)

    lines: list[str] = []
    lines.append("// Auto-generated MLP weights — do not edit manually")
    lines.append("// Generated by slm-os-page-sim")
    lines.append("")

    if quantize:
        lines.append("// Int8 quantized weights (scale factors embedded)")
        lines.append("")
        _emit_quantized_weights(layers, lines)
        lines.append("")
        _emit_quantized_inference(layers, lines)
    else:
        lines.append("// Float32 weights")
        lines.append("")
        _emit_float_weights(layers, lines)
        lines.append("")
        _emit_float_inference(layers, lines)

    source = "\n".join(lines)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(source)

    return source


def quantize_model(model: PageReplacementMLP) -> dict[str, np.ndarray]:
    """Apply post-training int8 quantization to MLP weights.

    Symmetric per-tensor quantization: scale = max(abs(tensor)) / 127.
    Returns dict of quantized arrays + scale factors.
    """
    state = model.state_dict()
    quantized: dict[str, np.ndarray] = {}

    for name, tensor in state.items():
        arr = tensor.cpu().numpy().astype(np.float32)
        scale = np.max(np.abs(arr)) / 127.0 if np.max(np.abs(arr)) > 0 else 1.0
        q = np.clip(np.round(arr / scale), -128, 127).astype(np.int8)
        quantized[f"{name}_q"] = q
        quantized[f"{name}_scale"] = np.array([scale], dtype=np.float32)

    return quantized


def compute_model_size(model: PageReplacementMLP, quantize: bool = True) -> int:
    """Compute model size in bytes."""
    total = 0
    for param in model.parameters():
        if quantize:
            total += param.numel()  # 1 byte per int8
            total += 4              # 4 bytes for scale factor per tensor
        else:
            total += param.numel() * 4  # 4 bytes per float32
    return total


def _extract_layers(
    state: dict[str, torch.Tensor],
) -> list[tuple[np.ndarray, np.ndarray]]:
    """Extract (weight, bias) pairs for each linear layer."""
    layers = []

    # Shared layers: shared.0 (Linear 27->64), shared.3 (64->32), shared.6 (32->16)
    layer_keys = [
        ("shared.0.weight", "shared.0.bias"),
        ("shared.3.weight", "shared.3.bias"),
        ("shared.6.weight", "shared.6.bias"),
        ("classify_head.0.weight", "classify_head.0.bias"),
    ]

    for w_key, b_key in layer_keys:
        if w_key in state and b_key in state:
            w = state[w_key].cpu().numpy()
            b = state[b_key].cpu().numpy()
            layers.append((w, b))

    return layers


def _emit_quantized_weights(
    layers: list[tuple[np.ndarray, np.ndarray]],
    lines: list[str],
) -> None:
    """Emit int8 weight arrays and scale factors."""
    layer_names = ["L1", "L2", "L3", "OUT"]

    for (w, b), name in zip(layers, layer_names):
        rows, cols = w.shape
        w_scale = np.max(np.abs(w)) / 127.0 if np.max(np.abs(w)) > 0 else 1.0
        b_scale = np.max(np.abs(b)) / 127.0 if np.max(np.abs(b)) > 0 else 1.0

        w_q = np.clip(np.round(w / w_scale), -128, 127).astype(np.int8)
        b_q = np.clip(np.round(b / b_scale), -128, 127).astype(np.int8)

        lines.append(f"pub const W_{name}_SCALE: f32 = {w_scale};")
        lines.append(f"pub const B_{name}_SCALE: f32 = {b_scale};")
        lines.append(f"pub const W_{name}: [[i8; {cols}]; {rows}] = [")
        for row in w_q:
            lines.append(f"    [{', '.join(str(v) for v in row)}],")
        lines.append("];")
        lines.append(f"pub const B_{name}: [i8; {rows}] = [{', '.join(str(v) for v in b_q)}];")
        lines.append("")


def _emit_quantized_inference(
    layers: list[tuple[np.ndarray, np.ndarray]],
    lines: list[str],
) -> None:
    """Emit the quantized inference function."""
    lines.append("/// MLP inference with int8 fixed-point arithmetic")
    lines.append("pub fn mlp_predict(features: &[f32; 27]) -> f32 {")
    lines.append("    // Layer 1: 27 -> 64, ReLU")
    lines.append("    let mut h1 = [0.0_f32; 64];")
    lines.append("    for i in 0..64 {")
    lines.append("        let mut acc = 0i32;")
    lines.append("        for j in 0..27 {")
    lines.append("            let input_q = (features[j] / W_L1_SCALE * 127.0) as i8;")
    lines.append("            acc += (W_L1[i][j] as i32) * (input_q as i32);")
    lines.append("        }")
    lines.append("        h1[i] = (acc as f32) * W_L1_SCALE * W_L1_SCALE / (127.0 * 127.0)")
    lines.append("            + (B_L1[i] as f32) * B_L1_SCALE;")
    lines.append("        if h1[i] < 0.0 { h1[i] = 0.0; }  // ReLU")
    lines.append("    }")
    lines.append("")
    lines.append("    // Layer 2: 64 -> 32, ReLU")
    lines.append("    let mut h2 = [0.0_f32; 32];")
    lines.append("    for i in 0..32 {")
    lines.append("        let mut acc = 0.0_f32;")
    lines.append("        for j in 0..64 {")
    lines.append("            acc += h1[j] * (W_L2[i][j] as f32) * W_L2_SCALE;")
    lines.append("        }")
    lines.append("        h2[i] = acc + (B_L2[i] as f32) * B_L2_SCALE;")
    lines.append("        if h2[i] < 0.0 { h2[i] = 0.0; }")
    lines.append("    }")
    lines.append("")
    lines.append("    // Layer 3: 32 -> 16, ReLU")
    lines.append("    let mut h3 = [0.0_f32; 16];")
    lines.append("    for i in 0..16 {")
    lines.append("        let mut acc = 0.0_f32;")
    lines.append("        for j in 0..32 {")
    lines.append("            acc += h2[j] * (W_L3[i][j] as f32) * W_L3_SCALE;")
    lines.append("        }")
    lines.append("        h3[i] = acc + (B_L3[i] as f32) * B_L3_SCALE;")
    lines.append("        if h3[i] < 0.0 { h3[i] = 0.0; }")
    lines.append("    }")
    lines.append("")
    lines.append("    // Output: 16 -> 1, Sigmoid")
    lines.append("    let mut out = 0.0_f32;")
    lines.append("    for j in 0..16 {")
    lines.append("        out += h3[j] * (W_OUT[0][j] as f32) * W_OUT_SCALE;")
    lines.append("    }")
    lines.append("    out += (B_OUT[0] as f32) * B_OUT_SCALE;")
    lines.append("    1.0 / (1.0 + (-out).exp())")
    lines.append("}")


def _emit_float_weights(
    layers: list[tuple[np.ndarray, np.ndarray]],
    lines: list[str],
) -> None:
    """Emit float32 weight arrays (for debugging / verification)."""
    layer_names = ["L1", "L2", "L3", "OUT"]

    for (w, b), name in zip(layers, layer_names):
        rows, cols = w.shape
        lines.append(f"pub const W_{name}: [[f32; {cols}]; {rows}] = [")
        for row in w:
            vals = ", ".join(f"{v:.6}" for v in row)
            lines.append(f"    [{vals}],")
        lines.append("];")
        vals = ", ".join(f"{v:.6}" for v in b)
        lines.append(f"pub const B_{name}: [f32; {rows}] = [{vals}];")
        lines.append("")


def _emit_float_inference(
    layers: list[tuple[np.ndarray, np.ndarray]],
    lines: list[str],
) -> None:
    """Emit float32 inference function (for verification)."""
    dims = [(w.shape[1], w.shape[0]) for w, _ in layers]
    names = ["L1", "L2", "L3", "OUT"]

    input_dim = dims[0][0]
    lines.append("/// MLP inference with float32 arithmetic (for verification)")
    lines.append(f"pub fn mlp_predict_f32(features: &[f32; {input_dim}]) -> f32 {{")

    prev_var = "features"
    for i, ((in_d, out_d), name) in enumerate(zip(dims, names)):
        is_last = i == len(dims) - 1
        var = f"h{i + 1}" if not is_last else "out"

        if is_last:
            # Output layer: scalar
            lines.append(f"    let mut {var} = 0.0_f32;")
            lines.append(f"    for j in 0..{in_d} {{")
            lines.append(f"        {var} += {prev_var}[j] * W_{name}[0][j];")
            lines.append("    }")
            lines.append(f"    {var} += B_{name}[0];")
            lines.append(f"    1.0 / (1.0 + (-{var}).exp())")
        else:
            lines.append(f"    let mut {var} = [0.0_f32; {out_d}];")
            lines.append(f"    for i in 0..{out_d} {{")
            lines.append(f"        let mut acc = 0.0_f32;")
            lines.append(f"        for j in 0..{in_d} {{")
            lines.append(f"            acc += {prev_var}[j] * W_{name}[i][j];")
            lines.append("        }")
            lines.append(f"        {var}[i] = acc + B_{name}[i];")
            lines.append(f"        if {var}[i] < 0.0 {{ {var}[i] = 0.0; }}  // ReLU")
            lines.append("    }")
            lines.append("")

        prev_var = var

    lines.append("}")
