"""Convert trained XGBoost model to Rust if-else chain (Section 7.1).

Dumps the XGBoost tree ensemble to JSON, then generates a Rust function
that implements the same decision logic as nested if-else statements.
Trees of depth 6 with 200 rounds produce ~12,800 decision paths which
compile to approximately 50KB of Rust code.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import xgboost as xgb


def export_xgb_to_rust(
    model: xgb.Booster,
    output_path: str | Path,
    function_name: str = "xgb_predict",
    feature_names: list[str] | None = None,
    standalone: bool = False,
) -> str:
    """Convert an XGBoost model to a Rust if-else function.

    Args:
        model: Trained XGBoost Booster.
        output_path: Path to write the generated Rust file.
        function_name: Name of the generated Rust function.
        feature_names: Feature names for readable variable access.
        standalone: If True, omit the SLM-OS-specific `use` import so the
            file compiles on its own (used by Rust verification harnesses).

    Returns:
        The generated Rust source code as a string.
    """
    # Dump trees to JSON
    tree_dump = model.get_dump(dump_format="json")
    trees = [json.loads(t) for t in tree_dump]

    feature_names = feature_names or [f"f{i}" for i in range(27)]
    # Build a name → index lookup so tree splits like "predicted_reuse_dist"
    # are mapped to the right array slot, not parsed as "f<index>".
    feature_index = {name: i for i, name in enumerate(feature_names)}

    lines: list[str] = []
    lines.append("// Auto-generated from XGBoost model — do not edit manually")
    lines.append(f"// Trees: {len(trees)}, generated by slm-os-page-sim")
    lines.append("")
    if not standalone:
        lines.append("use crate::mm::eviction_policy::BlockFeatures;")
        lines.append("")
    lines.append(f"/// XGBoost prediction: returns P(optimal eviction target)")
    lines.append(f"pub fn {function_name}(features: &[f32; {len(feature_names)}]) -> f32 {{")
    lines.append("    let mut sum = 0.0_f32;")
    lines.append("")

    for tree_idx, tree in enumerate(trees):
        lines.append(f"    // Tree {tree_idx}")
        lines.append(f"    sum += {{")
        _tree_to_rust(tree, lines, feature_index, indent=8)
        lines.append(f"    }};")
        lines.append("")

    lines.append("    // Sigmoid activation")
    lines.append("    1.0 / (1.0 + (-sum).exp())")
    lines.append("}")

    source = "\n".join(lines)

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(source)

    return source


def _tree_to_rust(
    node: dict[str, Any],
    lines: list[str],
    feature_index: dict[str, int],
    indent: int = 8,
) -> None:
    """Recursively convert a tree node to Rust if-else."""
    pad = " " * indent

    if "leaf" in node:
        lines.append(f"{pad}{node['leaf']}_f32")
        return

    # Internal node: split on a feature
    split_feature = node.get("split", "f0")
    split_value = node.get("split_condition", 0.0)
    yes_child = node.get("yes", 0)
    no_child = node.get("no", 0)

    # Map feature name to index. Prefer the explicit lookup; fall back to the
    # default "f<index>" convention (e.g. when feature_names was not supplied
    # at training time).
    if split_feature in feature_index:
        feat_idx = feature_index[split_feature]
        feat_access = f"features[{feat_idx}] /* {split_feature} */"
    elif split_feature.startswith("f") and split_feature[1:].isdigit():
        feat_idx = int(split_feature[1:])
        feat_access = f"features[{feat_idx}]"
    else:
        raise ValueError(
            f"Unknown split feature '{split_feature}' — not in feature_names "
            f"and not in default 'f<i>' form"
        )

    lines.append(f"{pad}if {feat_access} < {split_value}_f32 {{")

    # Find yes and no children
    children = node.get("children", [])
    yes_node = None
    no_node = None
    for child in children:
        if child.get("nodeid") == yes_child:
            yes_node = child
        elif child.get("nodeid") == no_child:
            no_node = child

    if yes_node:
        _tree_to_rust(yes_node, lines, feature_index, indent + 4)
    else:
        lines.append(f"{pad}    0.0_f32")

    lines.append(f"{pad}}} else {{")

    if no_node:
        _tree_to_rust(no_node, lines, feature_index, indent + 4)
    else:
        lines.append(f"{pad}    0.0_f32")

    lines.append(f"{pad}}}")


def dump_trees_json(model: xgb.Booster, output_path: str | Path) -> None:
    """Dump XGBoost trees to JSON for inspection."""
    tree_dump = model.get_dump(dump_format="json")
    trees = [json.loads(t) for t in tree_dump]
    Path(output_path).write_text(json.dumps(trees, indent=2))
