//! Reference Rust implementations of SLM-OS eviction policies.
//!
//! This crate ports the Python eviction policies and the CACHEUS expert
//! selector from `slm-os-page-sim` to Rust. It is intended as a drop-in
//! template for `runtime/src/mm/` in the SLM-OS repo.
//!
//! The four classical policies (LRU, LFU, SLM-heuristic) match the
//! Python implementations decision-for-decision; parity is enforced by
//! `tests/parity.rs`. The trained ML policies (XGBoost, MLP) live in
//! files generated by `python scripts/export_to_slmos.py`; pull them in
//! via the `generated_models` cargo feature.

pub mod block;
pub mod eviction_policy;
pub mod lru;
pub mod lfu;
pub mod slm_heuristic;
pub mod cacheus;

pub use block::{BlockMeta, BlockFeatures, PoolType};
pub use eviction_policy::EvictionPolicy;
pub use lru::LruPolicy;
pub use lfu::LfuPolicy;
pub use slm_heuristic::SlmHeuristicPolicy;
pub use cacheus::CacheusSelector;

// Generated ML models — pull in via `cargo build --features generated_models`
// after running `python scripts/export_to_slmos.py --output-dir slm_os_integration/src/generated/`.
#[cfg(feature = "generated_models")]
pub mod generated;
